name: Cypress Tests
on: [push, workflow_dispatch]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run TC 01.00 - User logins
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run --spec 'cypress/e2e/Test_Rafael/Tests_AutomationPratice/TC 01.00 - User logins.cy.js'
         browser: chrome
         
         
     - name: Run TC 01.01 - Product Adding
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run --spec 'cypress/e2e/Test_Rafael/Tests_AutomationPratice/TC 01.01 - Product Adding.cy.js'
         browser: chrome
