name: Add Action
on: 
 workflow_dispatch:
 
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
       
     - name: Run Cypress Test
       uses: cypress-io/github-action@v5
       with:
         command: npx cypress run 'cypress/e2e/Test_Rafael/Tests_AutomationPratice/TC 01.00 - User logins.cy.js'
         browser: chrome
